---
apiVersion: v1
kind: Service
metadata:
  name: gptwol-service
  namespace: app-gptwol
spec:
  selector:
    app: gptwol
  type: LoadBalancer
  ports:
    - name: gptwol-app
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
