---
apiVersion: v1
kind: Service
metadata:
  name: gptwol-service
  namespace: app-gptwol
spec:
  selector:
    app: gptwol
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000 # Serviceのポート
      targetPort: 5000 # Podのポート
      nodePort: 30000 # NodePortのポート